
const appwrite = require('node-appwrite');
const client = new appwrite.Client()
        .setEndpoint('https://api-app2.asta-bochum.de/v1')
        .setProject('campus_app')                
        .setKey('b4fb54159257ef612e72ab4e0330bdb0c1760d6f7a93bfe5b209fd174154ff0f38cf9a87a71d235dfb90987b0662342b7a069ba9fb5bad6105daa1a5784ad1470f4d5d1f4f6902367a28c0b4a7d5b9ef00a576038f29f3c219136169c5748ef3e1535fbf40641a7155ff7099ed8ec19d3843e66e46186980c8bb26a01a33218f');

const db = new appwrite.Databases(client);

const courses = [
    'Accounting and Auditing',
    'Allgemeine und vergleichende Literaturwissenschaft',
    'Angewandte Informatik',
    'Anglistik/Amerikanistik',
    'Applied IT Security',
    'Arbeits-, Organisations- und Wirtschaftspsychologie',
    'Archäologische Wissenschaften',
    'Bauingenieurwesen',
    'Biochemie',
    'Biodiversität',
    'Biologie',
    'Chemie',
    'Chinesisch',
    'Cognitive Science',
    'Computational Engineering',
    'Deutsch',
    'Development-Management',
    'Econometrics',
    'Economic Policy Consulting',
    'Elektrotechnik und Informationstechnik',
    'Empirische Mehrsprachigkeitsforschung',
    'Englisch',
    'Erziehungswissenschaft',
    'Ethics - Economics, Law and Politics',
    'European Culture and Economy (ECUE)',
    'European Master’s Programme in Human Rights and Democratisation (E.MA)',
    'Evangelische Theologie',
    'Film und audiovisuelle Medien',
    'Finance, Accounting, Auditing, Controlling & Taxation',
    'Gender Studies - Kultur, Kommunikation, Gesellschaft',
    'Geographie',
    'Geosciences',
    'Geowissenschaften',
    'Germanistik',
    'Geschichte',
    'Griechisch',
    'History, Philosophy and Culture of Science (HPS+)',
    'Human Resource Management',
    'Informatik',
    'International Gender Studies',
    'International Humanitarian Action',
    'International Political Economy of East Asia',
    'IT-Sicherheit / Informationstechnik',
    'IT-Sicherheit / Netze und Systeme',
    'Italienisch',
    'Japanisch',
    'Japanologie',
    'Katholische Theologie',
    'Klassische Archäologie',
    'Klassische Philologie',
    'Koreanistik',
    'Kriminologie, Kriminalistik und Polizeiwissenschaft',
    'Kultur, Individuum und Gesellschaft',
    'Kunstgeschichte',
    'Kunstgeschichte der Moderne und Gegenwart',
    'Lasers and Photonics',
    'Latein',
    'Linguistic Data Science',
    'Management & Consulting im Sport',
    'Management and Economics',
    'Maschinenbau',
    'Materials Science and Simulation',
    'Materialwissenschaft',
    'Mathematik',
    'Medienwissenschaft',
    'Medieval and Renaissance Studies',
    'Medizin',
    'Medizinphysik',
    'Molecular and Developmental Stem Cell Biology',
    'Molecular Science - Spectroscopy and Simulation',
    'Nationales und europäisches Wirtschaftsrecht',
    'Organizational Management',
    'Orientalistik - Islamwissenschaft',
    'Ostasienwissenschaften',
    'Pädagogik',
    'Philosophie',
    'Philosophie/praktische Philosophie',
    'Physik',
    'Politik, Wirtschaft und Gesellschaft',
    'Psychologie',
    'Public History',
    'Rechtswissenschaft',
    'Religionswissenschaft',
    'Romanische Philologie',
    'Russisch',
    'Russische Kultur',
    'Sales Engineering and Product Management',
    'Sinologie',
    'Slavische Philologie',
    'Sozialwissenschaft',
    'Spanisch',
    'Sport & Exercise Sciences for Health and Performance',
    'Sportwissenschaft',
    'Sprachen und Kulturen Ostasiens',
    'Subsurface Engineering',
    'Szenische Forschung',
    'Theaterwissenschaft',
    'Transformation of Urban Landscapes',
    'Umweltingenieurwesen',
    'Ur- und Frühgeschichte',
    'VAMoS: Computer-, Psycho- und Theoretische Linguistik',
    'Wirtschaft und Politik Ostasiens',
    'Wirtschafts- und Rohstoffarchäologie',
    'Wirtschafts- und Steuerrecht',
    'Wirtschaftswissenschaft',
  ];

for (const c of courses) {
    db.createDocument('data', 'study_courses', appwrite.ID.unique(), {pId: 0, name: c});
}